package handle;
public class Exception {
    public static void main(String[] args) {
        int a = 10, b = 5, c = 5;
        int x, y;
        try {
            x = a / (b - c);
            System.out.println("Answer is: " + x);
        } catch (ArithmeticException e) {
            System.out.println("excepton occured" +e);
            y=a / (b+c);
            System.out.println("ans is"+y);
        }
    }
}
